# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('user_story_id', models.IntegerField()),
                ('subject', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TaigaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.TextField()),
                ('token', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='copy_receiver',
            field=models.ManyToManyField(related_name='emailUser_copy', to='emailTracker.EmailUser'),
        ),
        migrations.AddField(
            model_name='email',
            name='receiver',
            field=models.ManyToManyField(related_name='emailUser_receiver', to='emailTracker.EmailUser'),
        ),
        migrations.AddField(
            model_name='email',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailUser_sender', to='emailTracker.EmailUser'),
        ),
    ]
