# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 14:56
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('user_story_id', models.IntegerField()),
                ('sender', models.EmailField(max_length=254)),
                ('receivers', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), size=None)),
                ('copy_receivers', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), size=None)),
                ('subject', models.CharField(max_length=100)),
                ('text_html', models.TextField()),
                ('text_plain', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
