# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='user_story_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
