# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taigauser',
            name='id',
        ),
        migrations.AlterField(
            model_name='taigauser',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
