# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailTracker', '0002_auto_20160406_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='project_id',
        ),
        migrations.AddField(
            model_name='email',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
