# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailTracker', '0003_auto_20160411_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('decription', models.CharField(blank=True, max_length=200, null=True)),
                ('is_blocked', models.BooleanField()),
                ('is_closed', models.BooleanField()),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('owner_username', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userstory_id', models.IntegerField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('decription', models.CharField(blank=True, max_length=200, null=True)),
                ('is_blocked', models.BooleanField()),
                ('is_closed', models.BooleanField()),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('owner_username', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
