# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailTracker', '0004_task_userstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('action', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='TaigaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='userstory',
            old_name='decription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner_username',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='owner_username',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='project_name',
        ),
        migrations.AddField(
            model_name='task',
            name='user_story',
            field=models.ForeignKey(blank=True, db_column='userstory_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='emailTracker.UserStory', verbose_name='user story'),
        ),
        migrations.CreateModel(
            name='PayloadTask',
            fields=[
                ('payload_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emailTracker.Payload')),
            ],
            bases=('emailTracker.payload', models.Model),
        ),
        migrations.CreateModel(
            name='PayloadUserStory',
            fields=[
                ('payload_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emailTracker.Payload')),
            ],
            bases=('emailTracker.payload', models.Model),
        ),
        migrations.AddField(
            model_name='payload',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='emailTracker.TaigaUser', verbose_name='by'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to='emailTracker.TaigaUser', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='emailTracker.Project', verbose_name='project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstory',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_user_stories', to='emailTracker.TaigaUser', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='project',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='emailTracker.Project', verbose_name='project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payloaduserstory',
            name='userstory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='emailTracker.UserStory', verbose_name='userstory'),
        ),
        migrations.AddField(
            model_name='payloadtask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='emailTracker.Task', verbose_name='task'),
        ),
    ]
