# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailTracker', '0006_auto_20160510_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='finish_date',
            new_name='finished_date',
        ),
    ]
