# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailTracker', '0007_auto_20160510_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('action', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='payload',
            name='by',
        ),
        migrations.RemoveField(
            model_name='payloadtask',
            name='payload_ptr',
        ),
        migrations.RemoveField(
            model_name='payloadtask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='payloaduserstory',
            name='payload_ptr',
        ),
        migrations.RemoveField(
            model_name='payloaduserstory',
            name='userstory',
        ),
        migrations.CreateModel(
            name='LogTask',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emailTracker.Log')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='emailTracker.Task', verbose_name='task')),
            ],
            bases=('emailTracker.log', models.Model),
        ),
        migrations.CreateModel(
            name='LogUserStory',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emailTracker.Log')),
                ('userstory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='emailTracker.UserStory', verbose_name='userstory')),
            ],
            bases=('emailTracker.log', models.Model),
        ),
        migrations.DeleteModel(
            name='Payload',
        ),
        migrations.DeleteModel(
            name='PayloadTask',
        ),
        migrations.DeleteModel(
            name='PayloadUserStory',
        ),
        migrations.AddField(
            model_name='log',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='emailTracker.TaigaUser', verbose_name='by'),
        ),
    ]
